name: Unstable Kernel

on:
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest

    env:
      CONFIG: laptop_defconfig

    steps:        
    - name: Checkout
      uses: actions/checkout@master
      
    - name: Initialization environment
      run: |
        sudo apt install build-essential flex bison libssl-dev bc kmod gcc-aarch64-linux-gnu
        
    - name: build Kernel
      run: |
        export ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu-
        make $CONFIG      
        make -j$(nproc)

    - name : Upload kernel image
      uses: actions/upload-artifact@master
      with:
        name:  kernel images
        path: arch/arm64/boot/Image*        
